### ISSUE TITLE
Why is this not a pull request to mushroom?

### ISSUE THREAD

**Issue by metbril** [phischdev/lovelace-mushroom-better-sliders#1]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

-

### Describe the solution you'd like

Just out of curiosity. Have you considered creating a pull request to Mushroom? So everyone can benefit from your improvements as well as the ones in the original repo? (You already are behing several commits)

**Comment by phischdev** [comment]
Hi @metbril,
Thanks for asking a very reasonable question.
I suggested this as a PR first ([here is the discussion](https://github.com/piitaya/lovelace-mushroom/issues/934)) but piitaya disagreed with my proposed changes, which is fine.

For everyone who finds this mod useful and wants an easy way to install it (like myself), I will keep it in HACS and try to update it from time to time.

**Comment by phischdev** [comment]
-
