### ISSUE TITLE
[Feature]: Migration Instructions

### ISSUE THREAD

**Issue by Garywoo** [phischdev/lovelace-mushroom-better-sliders#2]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I'm not sure how to migrate from the original package to this fork.

### Describe the solution you'd like

Clear instructions on how to migrate, without needing to rebuild my existing dashboards.

**Comment by phischdev** [comment]
Hi,
do you want to migrate your own fork on top of this one?
Or is your question how to install it in your home assistant instance?

**Comment by Garywoo** [comment]
The question I have is how to install this in my own HA instance, and upgrade my existing dashboards to use it.
