### ISSUE TITLE
[Feature]: Update to 2.7

### ISSUE THREAD

**Issue by googanhiem** [phischdev/lovelace-mushroom-better-sliders#4]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Would love them new features Mushroom cards, but your sliders are better! 

### Describe the solution you'd like

Would you update it?

### Describe alternatives you've considered

Not staying on this fork

### Additional context

Thanks!

**Comment by phischdev** [comment]
I will look into it as soon as I have time

**Comment by phischdev** [comment]
Update to 2.8 has been released
