### ISSUE TITLE
Hi - please specify a license to Kino

### ISSUE THREAD

**Issue by cyberhardt** [phischdev/lovelace-mushroom-better-sliders#6]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I know this is completely unrelated to this project, but I have not found any other method to communicate with you. I made a mirror of your Kino project that is hosted on sourceforge. I wanted to know whether you would like to license it under the GPLv2 or if you would like me to license it under the CC0 (or some other license). While the sourceforge repository says GPLv2, the actual program has no reference of it, and this is why I'm asking you about it.

### Describe the solution you'd like

-

**Comment by cyberhardt** [comment]
I'd also like to know the building instructions for the program

**Comment by phischdev** [comment]
Hi,
Thanks for your interest in this old project :)
Just use GPLv2 or whatever you like.

About building: You would need Visual Studio (not vs code) to run it. If it still can run 🤷

**Comment by cyberhardt** [comment]
> Hi, Thanks for your interest in this old project :) Just use GPLv2 or whatever you like.
> 
> About building: You would need Visual Studio (not vs code) to run it. If it still can run 🤷

Right, GPLv2 it shall be then. Any specific version of Visual Studio? or some specific commands

old or not, it's the only program I've found of its kind. extremely useful when you play games that don't have fullscreen.

**Comment by phischdev** [comment]
I have stopped using Windows long ago. Is it still working for you?

**Comment by cyberhardt** [comment]
> I have stopped using Windows long ago. Is it still working for you?

it's working as intended, yes, you can see some screenshots on the repository I made
